# Generated by Django 4.0.4 on 2022-05-30 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('slug', models.SlugField(max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='Фотографии')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('artikul', models.CharField(max_length=200, verbose_name='Артикул')),
                ('price', models.IntegerField(blank=True, default=True, null=True, verbose_name='Цена')),
                ('old_price', models.IntegerField(blank=True, default=True, null=True, verbose_name='Старая цена')),
                ('discount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Скидки')),
                ('description', models.CharField(blank=True, max_length=1000, verbose_name='Описание')),
                ('size_range', models.CharField(max_length=100, verbose_name='Размерный ряд')),
                ('composition', models.CharField(max_length=100, verbose_name='Состав ткани')),
                ('stock', models.PositiveIntegerField(verbose_name='Количество в линейке')),
                ('material', models.CharField(max_length=100, verbose_name='Материал')),
                ('bestceller', models.BooleanField(default=True, verbose_name='Хит продаж')),
                ('novelties', models.BooleanField(default=True, verbose_name='Новинки')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.category')),
            ],
            options={
                'ordering': ['name'],
                'index_together': {('id',)},
            },
        ),
    ]
