# Generated by Django 4.0.4 on 2022-06-06 05:31

import ckeditor.fields
import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion
import product.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Заголовок')),
                ('description', ckeditor.fields.RichTextField(blank=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, upload_to='products', verbose_name='Картинки')),
            ],
            options={
                'verbose_name_plural': 'О нас',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('image', models.ImageField(blank=True, upload_to='products', verbose_name='Картинка')),
            ],
            options={
                'verbose_name_plural': 'Категория',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Help',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(db_index=True, max_length=200, verbose_name='Вопросы')),
                ('answer', models.TextField(db_index=True, max_length=200, verbose_name='Ответы')),
                ('image_help', models.ImageField(blank=True, upload_to='products', verbose_name='Картинки')),
            ],
            options={
                'verbose_name_plural': 'Помощь',
            },
        ),
        migrations.CreateModel(
            name='Help_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_help', models.ImageField(blank=True, upload_to='products', verbose_name='Картинки')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_news', models.ImageField(blank=True, upload_to='products', verbose_name='Картинка')),
                ('header', models.CharField(blank=True, max_length=200, verbose_name='Заголовок')),
                ('description', ckeditor.fields.RichTextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.CreateModel(
            name='OurAdvantages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, upload_to='products', verbose_name='Картинка')),
            ],
            options={
                'verbose_name_plural': 'Наши преимущества',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='products', verbose_name='Картинки')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('artikul', models.CharField(max_length=200, verbose_name='Артикул')),
                ('price', models.IntegerField(default=True, null=True, verbose_name='Цена')),
                ('old_price', models.IntegerField(default=True, null=True, verbose_name='Старая цена')),
                ('discount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Скидки')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Описание')),
                ('size_range', models.CharField(max_length=100, verbose_name='Размерный ряд')),
                ('composition', models.CharField(max_length=100, verbose_name='Состав ткани')),
                ('stock', models.PositiveIntegerField(verbose_name='Количество в линейке')),
                ('material', models.CharField(max_length=100, verbose_name='Материал')),
                ('bestseller', models.BooleanField(default=True, verbose_name='Хит продаж')),
                ('novelties', models.BooleanField(default=True, verbose_name='Новинки')),
                ('favorites', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.category', verbose_name='Категории')),
            ],
            options={
                'verbose_name_plural': 'Продукт',
                'ordering': ['name'],
                'index_together': {('id',)},
            },
        ),
        migrations.CreateModel(
            name='PublicOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Заголовок')),
                ('description', ckeditor.fields.RichTextField(null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name_plural': 'Публичная офферта',
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='products', verbose_name='Картинка')),
                ('link', models.URLField(blank=True, max_length=150, null=True, verbose_name='Ссылка')),
            ],
            options={
                'verbose_name_plural': 'Слайдер',
            },
        ),
        migrations.CreateModel(
            name='ProductItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products', validators=[product.models.validate_even])),
                ('rgbcolor', colorfield.fields.ColorField(choices=[('#FA0DF3', 'Purple'), ('#000000', 'Black'), ('#141EFF', 'Blue'), ('#FF0D22', 'Red'), ('#00FF00', 'Green'), ('#FA7819', 'Brown'), ('#F7FA0A', 'Yellow'), ('#FFFFFF', 'White')], default='#FFFFFF', image_field=None, max_length=18, samples=None, verbose_name='Выбор цветов')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_item_image', to='product.product')),
            ],
            options={
                'verbose_name_plural': 'Картинка продукта',
            },
        ),
        migrations.CreateModel(
            name='ProductItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_range', models.CharField(blank=True, max_length=100, null=True, verbose_name='Размерный ряд')),
                ('quantity_in_line', models.IntegerField(blank=True, null=True, verbose_name='Количество в линейке')),
                ('Product_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_size', to='product.product')),
            ],
        ),
    ]
