# Generated by Django 4.0.4 on 2022-06-09 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footer',
            name='footer_Image',
            field=models.ImageField(blank=True, null=True, upload_to='products', verbose_name='Логотип Хедера'),
        ),
        migrations.AlterField(
            model_name='footer',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='products', verbose_name='Логотип Футера'),
        ),
    ]
