# Generated by Django 4.0.4 on 2022-06-07 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footer',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Ватсапп'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Скидки'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(null=True, verbose_name='Количество в линейке'),
        ),
    ]
