# Generated by Django 4.0.4 on 2022-05-31 11:15

from django.db import migrations, models
import django.db.models.deletion
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Категории'},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='bestceller',
            new_name='bestseller',
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, upload_to='products', verbose_name='Фотографии'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='products', verbose_name='Картинки'),
        ),
        migrations.CreateModel(
            name='ProductItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products', validators=[product.models.validate_even])),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_item_image', to='product.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_range', models.CharField(blank=True, max_length=100, null=True, verbose_name='Размерный ряд')),
                ('quantity_in_line', models.IntegerField(blank=True, null=True, verbose_name='Количество в линейке')),
                ('Product_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_size', to='product.product')),
            ],
        ),
    ]
