# Generated by Django 4.0.4 on 2022-06-03 10:55

import ckeditor.fields
import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_productitem_rgbcolor_product_rgbcolor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Заголовок')),
                ('description', ckeditor.fields.RichTextField(null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name_plural': 'Публичная офферта',
            },
        ),
        migrations.AlterModelOptions(
            name='about_us',
            options={'verbose_name_plural': 'О нас'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': 'Категория'},
        ),
        migrations.AlterModelOptions(
            name='help',
            options={'verbose_name_plural': 'Помощь'},
        ),
        migrations.AlterModelOptions(
            name='ouradvantages',
            options={'verbose_name_plural': 'Наши преимущества'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'verbose_name_plural': 'Продукт'},
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, upload_to='products', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.category', verbose_name='Категории'),
        ),
        migrations.AlterField(
            model_name='product',
            name='old_price',
            field=models.IntegerField(default=True, null=True, verbose_name='Старая цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=True, null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='rgbcolor',
            field=colorfield.fields.ColorField(choices=[('#FA0DF3', 'Purple'), ('#000000', 'Black'), ('#141EFF', 'Blue'), ('#FF0D22', 'Red'), ('#00FF00', 'Green'), ('#FA7819', 'Brown'), ('#F7FA0A', 'Yellow'), ('#FFFFFF', 'White')], default='#FFFFFF', image_field=None, max_length=18, samples=None, verbose_name='Выбор цветов'),
        ),
        migrations.DeleteModel(
            name='about_us_image',
        ),
    ]
