# Generated by Django 4.0.4 on 2022-06-08 12:51

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price_q', models.IntegerField(blank=True, default=True, null=True, verbose_name='Cтоимость')),
                ('quan_sum', models.IntegerField(blank=True, default=True, null=True, verbose_name='Общ Количество линеек:')),
                ('rebate', models.IntegerField(blank=True, default=True, null=True, verbose_name='Скидка')),
                ('sum_r', models.IntegerField(blank=True, default=True, null=True, verbose_name='Итого')),
                ('image', models.ImageField(blank=True, editable=False, null=True, upload_to='products/%Y/%m/%d', verbose_name='Фотография')),
                ('name', models.CharField(blank=True, editable=False, max_length=200, null=True, verbose_name='Название товара')),
                ('recolor', colorfield.fields.ColorField(default='#000000', editable=False, image_field=None, max_length=18, samples=None)),
                ('price1', models.IntegerField(blank=True, default=True, editable=False, null=True, verbose_name='Цена')),
                ('old_price', models.IntegerField(blank=True, default=True, editable=False, null=True, verbose_name='Старая цена')),
                ('product', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_product', to='product.product')),
                ('product_item', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_items', to='product.productitem')),
                ('product_item_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_items_image', to='product.productitemimage')),
            ],
        ),
    ]
