# Generated by Django 4.0.4 on 2022-06-09 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0002_alter_footer_footer_image_alter_footer_header_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('lastname', models.CharField(blank=True, max_length=100, null=True)),
                ('mail', models.CharField(blank=True, max_length=50, null=True, verbose_name='Почта')),
                ('num', models.CharField(blank=True, max_length=30, null=True, verbose_name='Номер')),
                ('country', models.CharField(blank=True, max_length=30, null=True, verbose_name='Страна')),
                ('city', models.CharField(blank=True, max_length=30, null=True, verbose_name='Город')),
                ('date_order', models.CharField(blank=True, max_length=30, null=True, verbose_name='Дата оформления')),
                ('status', models.CharField(choices=[('Оформлен', 'Оформлен'), ('Отменен', 'Отменен'), ('Новый', 'Новый')], db_index=True, default=('Новый', 'Новый'), max_length=255, verbose_name='Выбор из списка')),
            ],
        ),
        migrations.CreateModel(
            name='ProductItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(blank=True, default=0, null=True, verbose_name='Общая цена до учета скидок')),
                ('quantity', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('sum', models.IntegerField(blank=True, default=0, null=True, verbose_name='Количество линеек')),
                ('sum_quantity', models.IntegerField(blank=True, default=0, null=True, verbose_name='Количество всех товаров в линейках')),
                ('discounts', models.IntegerField(blank=True, default=0, null=True, verbose_name='Сумма всех скидок')),
                ('total', models.IntegerField(blank=True, default=0, null=True, verbose_name='Итого к оплате')),
                ('product', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, related_name='related_cart', to='product.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='order.order')),
            ],
        ),
    ]
